In [ ]:
import numpy as np   # Import NumPy with alias np

#create NumPay array from Python list
py_list= [1,2,3,4,5]
arr = np.array(py_list)

#Print the array
print("NumPy Array:", arr)

#Print its type
print("Type:", type(arr))

NumPy Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [ ]:
import numpy as np   # importing numpy library

# create a 1D array from 10 to 50 (excluding 50)
arr = np.arange(10, 50)

# print the array
print("Array:", arr)

# print shape and size
print("Shape of array:", arr.shape)   # shape tells dimensions
print("Size of array:", arr.size)     # size tells total elements

Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Shape of array: (40,)
Size of array: 40


In [ ]:
import numpy as np   # import numpy

# Create a 2D array (3 rows, 4 columns) filled with zeros
arr = np.zeros((3, 4), dtype=int)

print("Original Array (zeros):")
print(arr)

# Replace all zeros with fives
arr[:] = 5

print("\nUpdated Array (fives):")
print(arr)

Original Array (zeros):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Updated Array (fives):
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
import numpy as np

# Generate a 1D array of 15 random integers between 1 and 100
numbers = np.random.randint(1, 101, size=15)

print("Random Numbers:", numbers)

# Find maximum, minimum, and mean
max_val = numbers.max()
min_val = numbers.min()
mean_val = numbers.mean()

print("Maximum Value:", max_val)
print("Minimum Value:", min_val)
print("Mean Value:", mean_val)

Random Numbers: [64  3 42  9 54  4 76 90 87 85 45 72 43 65 57]
Maximum Value: 90
Minimum Value: 3
Mean Value: 53.06666666666667


In [ ]:
import numpy as np

# Create a NumPy array of numbers from 1 to 20
arr = np.arange(1, 21)

print("Original Array:", arr)

# Extract only even numbers using boolean indexing
even_numbers = arr[arr % 2 == 0]
print("Even Numbers:", even_numbers)

# Reverse the array using slicing
reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even Numbers: [ 2  4  6  8 10 12 14 16 18 20]
Reversed Array: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [ ]:
import numpy as np   # importing numpy library

# creating a NumPy array
arr = np.array([10, 20, 30, 40, 50])

# printing the whole array
print("Array:", arr)

# printing the first element
print("First element:", arr[0])

# printing the last element
print("Last element:", arr[-1])

Array: [10 20 30 40 50]
First element: 10
Last element: 50


In [ ]:
import numpy as np

# Create a 2D array of shape (4, 4) with numbers from 1 to 16
arr = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 Array:")
print(arr)

# Extract the first two rows and last two columns
sub_array = arr[:2, -2:]
print("\nFirst two rows and last two columns:")
print(sub_array)

# Replace the diagonal elements with 0
for i in range(len(arr)):
    arr[i, i] = 0

print("\nArray after replacing diagonal elements with 0:")
print(arr)

Original 4x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First two rows and last two columns:
[[3 4]
 [7 8]]

Array after replacing diagonal elements with 0:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [ ]:
import numpy as np

# Create an array of 25 random integers between 1 and 100
random_array = np.random.randint(1, 101, size=25)

print("Original Array:")
print(random_array)

# Sort the array using np.sort()
sorted_array = np.sort(random_array)

print("\nSorted Array:")
print(sorted_array)

Original Array:
[15 71 91 86 46 42 69 26 74 53  1 25 75 77 29 29 52 23 72 24 54 17 36 68
 42]

Sorted Array:
[ 1 15 17 23 24 25 26 29 29 36 42 42 46 52 53 54 68 69 71 72 74 75 77 86
 91]


In [ ]:
import numpy as np

# create a 1D array from 1 to 10
arr = np.arange(1, 11)

print("Array:", arr)

# find maximum value
print("Maximum:", np.max(arr))

# find minimum value
print("Minimum:", np.min(arr))

# find sum of all elements
print("Sum:", np.sum(arr))

Array: [ 1  2  3  4  5  6  7  8  9 10]
Maximum: 10
Minimum: 1
Sum: 55


In [ ]:
import numpy as np

# Create a 1D array with 36 elements (1 to 36)
arr_1d = np.arange(1, 37)

# Reshape into 6x6 (2D array)
arr_2d = arr_1d.reshape(6, 6)

print("Original 2D Array (6x6):")
print(arr_2d)

# Sum of each row (axis=1 → across columns)
row_sum = np.sum(arr_2d, axis=1)

# Sum of each column (axis=0 → across rows)
col_sum = np.sum(arr_2d, axis=0)

print("\nSum of each row:")
print(row_sum)

print("\nSum of each column:")
print(col_sum)


Original 2D Array (6x6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sum of each row:
[ 21  57  93 129 165 201]

Sum of each column:
[ 96 102 108 114 120 126]
